# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2020-11-18 04:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artista',
            fields=[
                ('nombre', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('detalles', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Cancion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('artista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Artista')),
            ],
        ),
        migrations.CreateModel(
            name='Estilo',
            fields=[
                ('nombre', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('detalles', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='cancion',
            name='estilo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Estilo'),
        ),
    ]
