# Generated by Django 3.1.1 on 2020-11-22 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_cancion_uri'),
    ]

    operations = [
        migrations.AddField(
            model_name='estilo',
            name='caratula',
            field=models.CharField(default='img/primavera.jpg', max_length=30),
        ),
    ]
