# Generated by Django 3.1.1 on 2020-11-22 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_estilo_caratula'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estilo',
            name='caratula',
            field=models.ImageField(upload_to='gallery'),
        ),
    ]
