# Generated by Django 3.1.1 on 2020-11-25 09:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_artista_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='cancion',
            name='caratula',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='gallery'),
            preserve_default=False,
        ),
    ]
