# Generated by Django 3.1.1 on 2020-11-25 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_cancion_caratula'),
    ]

    operations = [
        migrations.AddField(
            model_name='cancion',
            name='vecesEscuchada',
            field=models.IntegerField(default=0),
        ),
    ]
